database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: "admin1"
  url: jdbc:mysql://localhost:3306/mydb
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: true

server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091